# Generated 2026-03-31 from:
# C:\Projects\bitblind\asr\asr_transferability\attack_configs\pgd_multi_conformer.yaml
# yamllint disable
seed: 1002
__set_seed: !apply:torch.manual_seed [1002]
root: C:/Projects/bitblind/asr
tokenizers_folder: C:/Projects/bitblind/asr/tokenizers

# Attack parameters
snr: 5
nb_iter: 5000
rel_eps_iter: 0.05

attack_class: !name:robust_speech.adversarial.attacks.pgd.SNRPGDAttack
  targeted: false
  snr: 5
  nb_iter: 5000
  rel_eps_iter: 0.05
  train_mode_for_backward: true

attack_name: pgd_untargeted_conformer
save_audio: true
load_audio: false

# Three proxies - HuBERT + Wav2Vec2 + Conformer
source_model_name1: hubert-large-960h
source_model_name2: wav2vec2-large-960h-lv60-self
source_model_name3: conformer-mini-101

w2v_class: &id001 !name:robust_speech.models.wav2vec2_fine_tune.W2VASR
trf_class: &id002 !name:robust_speech.models.transformer.TrfASR


source_brain_class: &id003
- *id001
- *id001
- *id002
source_brain_hparams_file: &id004

- model_configs/wav2vec2/hubert-large-960h.yaml
- model_configs/wav2vec2/wav2vec2-large-960h-lv60-self.yaml
- model_configs/conformer/conformer-mini-101.yaml

source_ref_attack: 0
source_ref_train: 0
source_ref_valid_test: 0

target_brain_class: *id003
target_brain_hparams_file: *id004
pretrained_tokenizer_path: C:/Projects/bitblind/asr/trainings/hubert-large-960h
tokenizer: &id005 !new:speechbrain.dataio.encoder.CTCTextEncoder

pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
  collect_in: C:/Projects/bitblind/asr/tokenizers/hubert-large-960h
  loadables:
    tokenizer: *id005
  paths:
    tokenizer: 
      C:/Projects/bitblind/asr/trainings/hubert-large-960h/tokenizer.ckpt

output_folder: 
  C:/Projects/bitblind/asr/attacks/pgd_untargeted_conformer/hubert-large-960h-wav2vec2-large-960h-lv60-self-conformer-mini-101/1002
wer_file: 
  C:/Projects/bitblind/asr/attacks/pgd_untargeted_conformer/hubert-large-960h-wav2vec2-large-960h-lv60-self-conformer-mini-101/1002/wer.txt
save_folder: 
  C:/Projects/bitblind/asr/attacks/pgd_untargeted_conformer/hubert-large-960h-wav2vec2-large-960h-lv60-self-conformer-mini-101/1002
log: 
  C:/Projects/bitblind/asr/attacks/pgd_untargeted_conformer/hubert-large-960h-wav2vec2-large-960h-lv60-self-conformer-mini-101/1002/log.txt
save_audio_path: 
  C:/Projects/bitblind/asr/attacks/pgd_untargeted_conformer/hubert-large-960h-wav2vec2-large-960h-lv60-self-conformer-mini-101/1002/save

dataset_prepare_fct: !name:robust_speech.data.librispeech.prepare_librispeech
dataio_prepare_fct: !name:robust_speech.data.dataio.dataio_prepare
data_folder: C:/Projects/bitblind/asr/data/custom
csv_folder: C:/Projects/bitblind/asr/data/custom/csv
test_splits: [custom]
skip_prep: true
data_csv_name: custom
test_csv:
- C:/Projects/bitblind/asr/data/custom/csv/custom.csv
batch_size: 1
avoid_if_longer_than: 14.0
sorting: random

sample_rate: 16000
n_fft: 400
n_mels: 80
blank_index: 0
bos_index: 1
eos_index: 2

test_dataloader_opts:
  batch_size: 1

logger: !new:speechbrain.utils.train_logger.FileTrainLogger
  save_file: 
    C:/Projects/bitblind/asr/attacks/pgd_untargeted_conformer/hubert-large-960h-wav2vec2-large-960h-lv60-self-conformer-mini-101/1002/log.txt
